### ISSUE TITLE
No size saving suggestions found.

### ISSUE THREAD

**Issue by sd6352051** [android/size-analyzer#1]
Why does it always say "No size saving suggestions found."? I tested many  Android Studio projects  tips are the same.But I do know these projects have some problems 

build in windows 10

1. gradlew executableJar

2. java -jar build/libs/analyzer.jar check-project G:\user\my_project_path

**Comment by UdamSaini** [comment]
There are a few size suggestion savings that are implemented that you can see working by trying it out on this project: https://github.com/kickstarter/android-oss for instance.

If you run that same command: java -jar build/libs/analyzer.jar check-project /pathto/android-oss-master/
You should find a few size savings suggestion, mainly concerning dynamically delivering large files and webp image conversion.

That said, this project is still a heavy work in project, and there are many size suggestions we have planned that we have not yet implemented.

We also welcome suggestions and code contributions if there are any that you may have.
