### ISSUE TITLE
Compatibility with `IntelliJ IDEA Ultimate Edition`

### ISSUE THREAD

**Issue by htbkoo** [android/size-analyzer#11]
**Is your feature request related to a problem? Please describe.**
So my main IDE is actually `IntelliJ IDEA Ultimate Edition`. 
I had [tried to install this](https://developer.android.com/topic/performance/reduce-apk-size#as-analyzer) today but it had failed due to incompatibility

I believe `Android Studio` actually shares the same codebase with `IntelliJ IDEA Community Edition` and thus I wonder if it would be possible to make this plugin compatible with `IntelliJ IDEA Ultimate Edition` / `IntelliJ IDEA Community Edition`

**Is your feature request related to a new size savings suggestion? Please describe.**
N/A

**Describe the solution you'd like**
This plugin is made compatible with `IntelliJ IDEA Ultimate Edition` and we can install it.

**Describe alternatives you've considered**
An alternative would be to use `Android Studio` instead but this could be very inconvenient because there are quite a lot of exclusive features that are only available in `IntelliJ IDEA Ultimate Edition`

**Additional context**
Currently we could not find this plugin in the `Marketplace` search:
<img width="1094" alt="Screenshot 2020-06-12 at 15 41 00" src="https://user-images.githubusercontent.com/11581279/84479355-674f3380-acc5-11ea-9c24-510ffee93cfd.png">

And if we tried to install the jar manually from disk, it would fail due to this incompatibility error:
<img width="456" alt="Screenshot 2020-06-12 at 15 41 13" src="https://user-images.githubusercontent.com/11581279/84479360-69b18d80-acc5-11ea-9f77-648a9c3f3017.png">

Thanks a lot for the effort in creating this plugin - I would be really grateful if we can use it in `IntelliJ IDEA Ultimate Edition` as well!

(Please let me know if this is duplicated / already covered somewhere else and I would close this - I had tried to search for `intellij` in the `Issues` page but found nothing)

**Comment by tdeck** [comment]
I'm sorry that this bug was left open for so long. Those of us who built the size analyzer have moved on to different projects.

In this particular case, your best option is to use the size analyzer CLI. Our plugin uses some Android-specific extensions in Android Studio that wouldn't be compatible with IJUE.
