### ISSUE TITLE
Android App Analyzer not working on large projects

### ISSUE THREAD

**Issue by jayshildave1983** [android/size-analyzer#14]
**Describe the bug**
Project having a release APK size around 61 MB(with proguard) for two architectures 'armeabi-v7a', 'arm64-v8a'. It doesnt give any output

**Size-Analyzer version(s) affected**
Version: 0.3.0

**Stacktrace**
None available through plugin within Android Studio 4.0.1

**To Reproduce**
Just try execute Android App Analyzer by selected app -> Analyze -> Analyze App Size

**Expected behavior**
Some sort of loader or indication need to be shown

**Known workaround**
No workaround found

**Environment:**
Mac OS: 10.15.4 

**Additional context**
Works on smaller projects

**Comment by tdeck** [comment]
Thanks for reporting this, and I'm sorry that it's taken so long to get a reply. We don't have the resources to maintain this project anymore, and in fact the plugin was never updated to run on more recent versions of Android Studio. This is a real problem, but I'm going to close this bug. You may have better luck with the CLI version which is still available from this repo.

**Comment by deathfish** [comment]
same problem
