### ISSUE TITLE
Plugin incompatible with Android Studio 3.6.1

### ISSUE THREAD

**Issue by benju69** [android/size-analyzer#8]
**Describe the bug**
Plugin incompatible with Android Studio 3.6.1

**Size-Analyzer version(s) affected**
Version: 0.3.1

**Stacktrace**

**To Reproduce**
Update AS 3.5 

**Expected behavior**
working

**Workaround**
AS 3.6 downgrade to version 0.3.0

**Environment:**
OS: macOS

**Additional context**
![Screenshot 2020-03-09 at 14 23 31](https://user-images.githubusercontent.com/2486590/76216836-94490180-6211-11ea-8bf3-c6b67c08f95b.png)

**Comment by stoyicker** [comment]
Not working on Ubuntu 19.10 either. The window that should show does not. I cannot tell whether it worked on 3.5 or not, though.

**Comment by varunajaygupta** [comment]
I am also facing the same issue i have updated the Android studio to the latest 3.4.0. Still facing the same issue.

**Comment by tdeck** [comment]
Unfortunately this project hasn't had engineering resources for a long time, so we haven't been able to maintain the plugin to keep up with changes in Android Studio's APIs. The internal Studio / IntelliJ APIs are not stable so this can be a big job. For this reason I've removed the plugin from the repo and deprecated it in the JetBrains marketplace.
